name: front-linter
on:
  # Triggers the workflow on push or pull request on any branch
  pull_request:
    branches: '**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ''
      - name: install
        run: yarn install
      - name: ESLint
        run: yarn run fix .
      - name: Prettier
        run: yarn prettier --write .
