name: Lint

on:
  pull_request:
    branches:
      - "**"

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install Node.js dependencies
        run: npm ci

      - name: Set up eslint, prettier, and Babel dependencies
        run: |
          npm install --save-dev eslint eslint-config-react-app prettier eslint-plugin-prettier eslint-config-prettier
          npm install --save-dev @babel/plugin-proposal-private-property-in-object

      - name: Run ESLint
        run: npm run lint
        continue-on-error: true

      - name: Display ESLint output
        if: failure()
        run: cat eslint-report.json

      - name: Run Prettier
        run: npm run prettier
        continue-on-error: true

      - name: Display Prettier output
        if: failure()
        run: cat prettier-report.txt
